# Generated by Django 3.2.16 on 2023-05-04 11:56
import logging

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payer', '0005_alter_funding_date_created_and_more'),
    ]

    operations = [
    ]
